exports/Pages/_config.yml, exports/Pages/pages/AU-19.md, renderers/certifications_to_pages.py, renderers/yamls_to_certification.py
Sort controls in navigation bar alphabetically. 
[Resolves #23]
=> Sorting markdowns

README.md
=> First draft of documentation update

data/components/AWS/VPC.yaml
Removed CM-2 section as it is more Cloud Formation info
Added details to SC-7b for VPC
=> Add VPC component data

data/components/AWS/ACL.yaml
=> Update the ACL component

data/components/AWS/VisualOps.yaml
No new information, just update layout
=> Update visualops component

data/components/AWS/SophosUTM.yaml
FYI: In the document, there are two subsections with almost the same
text. This commit reflects that has both subsections
=> Update sophos component

fixtures/docs/README.md, fixtures/docs/SUMMARY.md, fixtures/docs/content/AC.md, fixtures/docs/content/NIST-800-53-CM-2.md, src/renderers/certifications_to_gitbook.py, src/templates/standards/NIST-800-53.yaml, tests/test_cli.py
- organizing documentation by control family first to make it easier to read. 
- remove documentation that isn't complete (gap analysis will be done in another tool)
[Resolves #73]
=> Add Tab Feature to highlight control families

src/renderers/certifications_to_gitbook.py, tox.ini
This switch will change after updating the renderer.
=> Adding a try and except to catch multiple types of paths, 

CONTRIBUTING.md, README.md
The main change here is separating the instructions for people using the CLI from those who wish to contribute to it. Also added instructions for dependencies.
/cc @harrisj @davidebest
=> tweak setup instructions

masonry-go.go
Version should be 1.0.0, this commit should be versioned.
=> Updating compliance-masonry version

README.md
@jcscottiii This works locally for me now, it didn't before.
=> Going through this again, adjusted some instructions

README.md
The blog post has great explanation and background info! Also spelling out CLI, since government and tech have so many abbreviations and acronyms to keep track of.
=> Link to new blog post in readme

docs.go, docs/docs.go, docs/docs_suite_test.go, docs/docs_test.go, masonry-go.go
=> move docs file into its own package

docx/docx.go, gitbook/gitbook.go, gitbook/gitbookCertification.go, gitbook/gitbookComponents.go, gitbook/gitbookComponents_test.go, gitbook/gitbookSummaries.go, inventory/inventory.go, models/common/references.go, models/common/references_test.go, models/components.go, models/components/README.md, models/components/versions/base/component.go, models/components_test.go, models/justifications.go
This patch is the beginning of enabling multiple versions by
abstracting the logic to a common interface between versions
=> Move to using interface for component, satisfies

docx/docx.go, fixtures/component_fixtures/v3_0_0/EC2/component.yaml, fixtures/component_fixtures/v3_0_0/EC2WithKey/component.yaml, gitbook/gitbookCertification.go, models/components/versions/2_0_0/component.go, models/components/versions/2_0_0/component_test.go, models/components/versions/3_0_0/component.go, models/components/versions/3_0_0/component_test.go, models/components/versions/base/component.go, models/components/versions/parse.go, models/components/versions/parse_test.go
This depends on #159 
This patch introduces the following fields to the component.yaml: `parameters` `responsible_role`
This patch modifies the following fields: `narrative`
`narrative` now contains two fields: `key` and `text`. the `key` field is optional
`parameters` now contains two fields: `key` and `text`. both fields are required if used.
`responsible_role` is a single string.
These new fields are what make the 3.0.0 version schema of component.yaml
This PR does not change currently how the information is rendered to gitbook or docx. That will come in a subsequent PR.
An example schema for 3.0.0 is as follows:
```yaml
documentation_complete: false
name: Amazon Elastic Compute Cloud
key: EC2
references:
- name: Reference
path: http://VerificationURL.com
type: URL
satisfies:
- …
```
=> V3 0 0 component

CONTRIBUTING.md, masonry-go.go
=> fix version number

diff.go, masonry-go.go, masonry-go_test.go
- Added new lines to all of cli messages while sending output to `app.Writer`
Resolves #167
=> Added newline to cli messages

README.md
Fixes https://github.com/opencontrol/compliance-masonry/issues/186.
See commits.
/cc @cmc333333
=> fix README instructions around the dependencies 

.goxc.json, masonry-go.go
Addresses #193  cc @pburkholder
=> Increment version to 1.1.2

README.md
=> fix reference to supported schema versions

.codeclimate.yml, README.md
=> add Code Climate configuration

commands/docs/gitbook/gitbookCertification.go, lib/components_test.go, lib/result/justifications.go, lib/result/justifications_test.go, lib/workspace.go, lib/workspace_test.go
Builds on #215 
This package is a location of all the data that has been added from all
the data loaded in and should be separated from the regular data in lib/
=> Move justification to result package

commands/diff/inventory.go, commands/docs/gitbook/gitbook.go, commands/docs/gitbook/gitbookCertification.go, commands/docs/gitbook/gitbookCertification_test.go, commands/docs/gitbook/gitbookComponents.go, commands/docs/gitbook/gitbookSummaries.go, lib/certifications.go, lib/common/verifications.go, lib/common/verifications_test.go, lib/common/workspace.go, lib/components.go, lib/components/parse_test.go, lib/components_test.go, lib/result/justifications.go, lib/result/justifications_test.go, lib/standards.go, lib/standards_test.go, lib/workspace.go, lib/workspace_test.go
Builds on #225 
This patch also moves verifications to common from lib/result
=> Create Workspace interface and make LocalWorkspace private

CONTRIBUTING.md, README.md
Addresses feedback from https://github.com/opencontrol/compliance-masonry/pull/232.
/cc @jcscottiii @brittag
=> simplify install instructions

docs/usage.md
/cc @jcscottiii https://github.com/opencontrol/schemas/issues/24
=> add disclaimer about gap analysis

.gitignore, Makefile, build-all.sh, docs/development.md
Adds a Makefile and updates some documentation.
=> Add Makefile

.goreleaser.yml
- GoReleaser is a release automation tool for Go projects, the goal is to simplify the build,
release and publish steps while providing variant customization options for all steps.
See https://goreleaser.com/
=> Use GORELEASER

pkg/cli/export/export_test.go
- Amount of output was hitting output limitations for test platforms
=> Suppress Export Test Log Output

.goreleaser.yml
- Add license and readme docs
- Use zip for Windows
=> Fix goreleaser archiving

appveyor.yml
creates key with appropriate repo permissions
=> update AppVeyor build key
