opencontrol/compliance-masonry

data/standards/NIST-800-53.yaml
I've update NIST-800-53.yaml with full text of control from NIST SP 800-53. The YAML file is generated 
[GovReady/800-53-server](https://github.com/GovReady/800-53-server) via the call
```
http://localhost:8080/controllist/?ids=AC-2,AC-3,AC-6,AU-2,AU-6,CA-8,CM-2,CM-3,CM-6,CM-7,IA-2,PL-8,RA-5,SA-22,SC-7,SC-13,SI-2,SI-4,SI-10&format=control-masonry
```
The content is parsed from https://github.com/GovReady/800-53-server/blob/master/data/800-53-controls.xml document
=> Improve content of NIST-800-53.yaml

data/certifications/FISMA.yaml, exports/Pages/_config.yml, exports/certifications/FISMA.yaml, renderers/certifications_to_pages.py
Modified `renderers/certifications_to_pages.py` to check if `meta` key existed for a control before trying to look up control name. Replaces missing name with zero length string and generates log error to standout out so pages will still be generated.
Unfortunately, this solution does result in missing pages for a control with no name.
=> Closes #17. Check for info keys for listed controls.

exports/Pages/_config.yml, exports/Pages/pages/AU-19.md, renderers/certifications_to_pages.py
Split `create_markdown` into `create_standard_markdown` and `create_control_markdown` this allows for more data (even though it's incomplete) to flow into the static site markdowns.
=> Split markdown functions

src/templates/standards/PCI-DSS-MAY-2015.yaml
Added the PCI-DSS-MAY2015 standards in the same yaml format used for the NIST-800-53 standard.
Adapted from this source.
https://www.pcisecuritystandards.org/documents/Prioritized_Approach_v3-1.xlsx
=> Adding the PCI-DSS Standard in the same yaml format

CONTRIBUTING.md, README.md
* Formatting fixes in the README
* Fixing headings
* Fixing some formatting issues
* etc.
* Moved developer-focused documentation to CONTRIBUTING.md
* Simplified the developer setup instructions (use the repository fetched via `go get` instead of making a new one).
=> documentation cleanup

README.md, circleci/coverage.sh
For fork PRs, circleci will suppress the token to upload a coverage report. Codecov allows you to upload the report without a token because it has internal apis circleci.
Also, coveralls does not seem to be working recently as smoothly as usual lately.
=> Move to using codecov

fixtures/component_fixtures/common/EC2VersionNotSemver/component.yaml, gitbook/gitbookComponents_test.go, models/components/README.md, models/components/versions/2_0_0/component.go, models/components/versions/2_0_0/component_test.go, models/components/versions/base/component.go, models/components/versions/parse.go, models/components/versions/parse_test.go, models/opencontrol.go, tools/constants/constants.go
From #158 
Depends on #157 
> Also adds tests cases for non 2.0.
This patch allows someone to use float for only version 2.0 (for backwards compatibility). Otherwise it will error.
=> Enable semver instead of float32; Take II

diff.go, docs/docs.go, docs/docs_test.go, docx/docx.go, docx/docx_test.go, gitbook/gitbook.go, gitbook/gitbookCertification_test.go, gitbook/gitbookSummaries.go, gitbook/gitbookSummaries_test.go, inventory/inventory.go, inventory/inventory_test.go, masonry-go.go, masonry-go_test.go, models/components/versions/parse.go, models/components/versions/parse_test.go, models/opencontrol.go, models/opencontrol_test.go, tools/certifications/certifications.go, tools/constants/constants.go
This patch cleans up error handling.
It fixes #147 deprecation message.
It makes more methods return error (beforehand the methods returned nothing) 
It fixes methods that returned []string to represent both warnings and strings in one data structure, now methods will return a string for warning and []error for errors.
Instead of returning a generic schema message, it will print out the filename as well as the yaml error for easier debugging
=> V3 0 0 cli errors

README.md
=> include instructions about how to view gitbook locally

fixtures/component_fixtures/v3_0_0/EC2/component.yaml, fixtures/component_fixtures/v3_0_0/EC2WithKey/component.yaml, fixtures/exports_fixtures/complete_export/standards/NIST-800-53-CM-2.md, fixtures/exports_fixtures/complete_export/standards/PCI-DSS-MAY-2015-1.1.md, fixtures/exports_fixtures/complete_export/standards/PCI-DSS-MAY-2015-2.1.md, fixtures/exports_fixtures/complete_export_with_markdown/standards/NIST-800-53-CM-2.md, fixtures/exports_fixtures/complete_export_with_markdown/standards/PCI-DSS-MAY-2015-1.1.md, fixtures/exports_fixtures/complete_export_with_markdown/standards/PCI-DSS-MAY-2015-2.1.md, fixtures/opencontrol_fixtures/components/EC2/component.yaml, fixtures/opencontrol_fixtures_with_markdown/components/EC2/component.yaml, gitbook/gitbookCertification.go, gitbook/gitbookCertification_test.go, models/components/versions/2_0_0/component.go, models/components/versions/2_0_0/component_test.go, models/components/versions/3_0_0/component.go, models/components/versions/3_0_0/component_test.go, models/components/versions/base/component.go
This PR:
- Introduces the `control_origin` field
- Renders the `control_origin` field to the gitbook
This PR will **NOT** change rendering to docx because we are still debating how to handle the checkboxes.
=> Add control_origin to v3 and gitbook rendering of control_origin

README.md
A general overview of how the `markdowns` folder works. Looking back it this feature might be better understood if it was called `gitbook_base` or something similar. 
Resolves #183
=> Document `markdowns` feature

models/components/versions/parse.go, models/components/versions/parse_test.go
An invalid component.yaml currently results in an error like this:
```
Unable to parse component. Please check component.yaml schema for version 3.0.0
``` 
without providing the path or the line number (Urgh!). Now we'll get:
```
Unable to parse component. Please check component.yaml schema for version 3.0.0
File: opencontrols/components/AU_policy/component.yaml
Parse error: yaml: unmarshal errors:
line 12: cannot unmarshal !!map into []component.NarrativeSection
```
with filename, line number and error. Much better!
Also tried to make test cases more readable.  `go fmt` seems okay with the way I've done linebreaks (the rest of the file needs some `fmt` help, but that's another PR)
=> Useful error messages for the holiday weekend

tools/mapset/map.go, tools/mapset/map_test.go
I thought it might be handy to have both my standards and my certifications in the same repo:, https://github.com/pburkholder/freedonia-frist, and then refer to them in my `opencontrol.yaml` as follows, from 
```yaml
dependencies:
standards:
- url: https://github.com/pburkholder/freedonia-frist/
revision: master
certifications:
- url: https://github.com/pburkholder/freedonia-frist/
revision: master
```
When I tried this I got the following:
```bash
$ compliance-masonry --verbose get
2016/07/07 14:18:08 Running with verbosity
2016/07/07 14:18:08 Retrieving certifications
2016/07/07 14:18:08 Retrieving standards
2016/07/07 14:18:08 Retrieving components
2016/07/07 14:18:08 Ensuring directory /Users/pburkholder/Projects/pburkholder/freedonia-compliance/opencontrols/components exists …
```
=> Fix "Already exists" error when sharing single repo for standards and certifications

README.md
All of the other information about the file schemas are in the schemas repository, so removing the opencontrol.yaml information here to be consistent. Depends on https://github.com/opencontrol/schemas/pull/36.
=> remove schema information for the opencontrol.yaml

fixtures/component_fixtures/v3_1_0/EC2/component.yaml, fixtures/component_fixtures/v3_1_0/EC2WithKey/component.yaml, models/components/versions/2_0_0/component.go, models/components/versions/2_0_0/component_test.go, models/components/versions/3_0_0/component.go, models/components/versions/3_0_0/component_test.go, models/components/versions/3_1_0/component.go, models/components/versions/3_1_0/component_test.go, models/components/versions/base/component.go, models/components/versions/parse.go, models/components/versions/parse_test.go
This PR:
- Retroactively adds support for `implementation_status` to schema versions `2.0.0` and `3.0.0`. 
- The schema already had this field but masonry did not support it.
- Introduces schema version `3.1.0` as per https://github.com/opencontrol/schemas/issues/25
- Introduces `control_origins` and `GetControlOrigins()` interface method to Satisfies base interface.
- Introduces `implementation_statuses` and `GetImplementationStatuses()` interface method to Satisfies base interface
=> Update schema for control_origin and implementation_status

tools/fs/fs.go
it makes the return value always nil
=> shadowed `err` variable created

CONTRIBUTING.md
They now work by default.
This is super minor, but I'm also seeing "Dependency golang.org/x/sys/unix failed to resolve" but as I'm not sure if it has to do with my versions of libraries, I didn't want to create an issue. The tests seem to run for me, though.
=> The --update-vendored and --strip-vcs flags are deprecated.

README.md
Addresses #179
Inspired by:
https://www.terraform.io/intro/getting-started/install.html
http://gohugo.io/overview/installing/
http://gohugo.io/tutorials/installing-on-mac/
http://gohugo.io/tutorials/installing-on-windows/
=> Add binary installation instructions

.dockerignore, Dockerfile, docs/usage.md
Adding Dockerfile and .dockerignore for initial Docker support.
CC @afeld
=> Initial Docker support

circle.yml, lib/workspace.go, masonry-go.go, masonry-go_test.go
* Run [errcheck](https://github.com/kisielk/errcheck) through Circle CI
* Ensure that errors are handled in code, or at least explicitly ignore them (in tests)
=> ensure that errors are handled

docs/install.md
On enterprise linux distros, the /usr/local/bin/ directory is protected from non-privileged users. Need sudo to copy files into that directory.
`````
$ cp compliance-masonry_1.1.2_linux_amd64/compliance-masonry /usr/local/bin/
cp: cannot create regular file ‘/usr/local/bin/compliance-masonry’: Permission denied
`````
This patch updates the install example to use sudo.
=> Update Linux install commands with sudo

commands/docs/gitbook/gitbookCertification.go, commands/docs/gitbook/gitbookCertification_test.go, fixtures/exports_fixtures/complete_export/standards/NIST-800-53-AC-2.md, fixtures/exports_fixtures/complete_export/standards/NIST-800-53-AC-6.md, fixtures/exports_fixtures/complete_export/standards/NIST-800-53-CM-2.md, fixtures/exports_fixtures/complete_export/standards/PCI-DSS-MAY-2015-1.1.1.md, fixtures/exports_fixtures/complete_export_with_markdown/standards/NIST-800-53-AC-2.md, fixtures/exports_fixtures/complete_export_with_markdown/standards/NIST-800-53-AC-6.md, fixtures/exports_fixtures/complete_export_with_markdown/standards/PCI-DSS-MAY-2015-1.1.1.md, fixtures/opencontrol_fixtures/standards/NIST-800-53.yaml, lib/common/control.go, lib/common/mocks/Control.go, lib/standards/standard_test.go, lib/standards/versions/1_0_0/standard.go, lib/standards/versions/1_0_0/standard_test.go
Related:
https://github.com/opencontrol/schemas/pull/56
https://github.com/opencontrol/schemas/issues/60
Based on a slack conversation with @anweiss, this PR adds compliance-masonry support for a "description" field for standards, based on the v1.0.0 schema.  [NIST-800-53 standards](https://github.com/opencontrol/NIST-800-53-Standards/blob/master/NIST-800-53.yaml) have already added the field as an example.
This PR also adds the description to the top of each standard page in the generated gitbook documentation.  For example:
=> Update standard v1.0.0 to include "description" field

Dockerfile
My git repo is tied to ssh so this version of compliance-masonry supports that. Permits me to do:
```
schema_version: "1.0.0"
name: freedonia.fd
[...]
dependencies:
standards:
- url: ssh+git://git@gitclone.hlsdev.local/demos/comp-masonry-freedonia-stds.git
revision: master
certifications:
- url: ssh+git://git@gitclone.hlsdev.local/demos/comp-masonry-freedonia-certs.git
revision: master
[...]
```
=> Added openssl for git ssh support

commands/get/resources/getter.go
Fixes https://github.com/opencontrol/compliance-masonry/issues/257.
(Doesn't occur elsewhere in the codebase.)
=> Fix reursively spelling.

Gopkg.lock, Gopkg.toml, tools/fs/fs.go
Replaced the 3 calls to go-utils/ufs with metalapp/go-util.
Only difference was adding an empty string in call to CopyAll for the 4th skipFileSuffix parameter.
Renamed the import to meatleapfs to prevent overlaps.
Complied and Tested on macOS High Sierra 10.13.2
∴ go version
go version go1.9.3 darwin/amd64
=> Replaced 3 calls to go-utils/ufs with metaleap/go-util 

commands/get/resources/getter.go, commands/get/resources/getter_test.go, lib/common/mocks/RemoteSource.go, lib/common/opencontrol.go, lib/opencontrol/versions/1.0.0/opencontrol.go
This allows for multiple opencontrol directories in a single git repository.
=> Add contextdir for multi-directory git handling

commands/get/resources/getter.go
Code was in the wrong location which was causing the clone to happen incorrectly.
=> Fix location of contextdir path code

commands/get/resources/getter.go, commands/get/resources/getter_test.go, lib/certifications/certification_test.go, lib/certifications/versions/1_0_0/certification_test.go, lib/common/mocks/RemoteSource.go, lib/components/parse_test.go, lib/components/versions/3_0_0/component_test.go, lib/components/versions/3_1_0/component_test.go, lib/opencontrol/versions/1.0.0/opencontrol.go, lib/opencontrol/versions/1.0.0/opencontrol_test.go, lib/standards/versions/1_0_0/standard_test.go
=> gofmt code updates

.circleci/config.yml, Makefile, appveyor.yml, cmd/compliance-masonry/compliance-masonry.go, cmd/masonry/masonry.go, cmd/masonry/masonry_suit_test.go, cmd/masonry/masonry_test.go, examples/example_test.go, pkg/cmd/masonry/cmd.go, pkg/tests/test_masonry.go
- Create a new compliance-masonry executable for legacy uses
- New masonry.go is now the primary program naming
- Fixes #177
=> Rename executable to masonry

cmd/masonry/masonry_test.go, pkg/cli/export/export.go, pkg/cli/export/exportFormat.go, pkg/cli/export/export_config.go, pkg/cli/export/export_flatten.go, pkg/cli/export/export_outputFormat.go, pkg/cli/export/export_suite_test.go, pkg/cli/export/export_test.go, pkg/cli/export/export_utility.go, pkg/cmd/masonry/cmd.go, pkg/lib/certifications/certification.go, pkg/lib/certifications/versions/1_0_0/certification.go, pkg/lib/common/mocks/Workspace.go, pkg/lib/common/workspace.go, pkg/lib/standards.go, tools/constants/constants.go
=> Add export option

.codeclimate.yml
- Files in mocks/ directories are autogenerated so we shouldn't care about evaluating code quality.
=> Exclude mocks/ directories from codeclimate

cmd/masonry/masonry_test.go, pkg/cmd/masonry/cmd.go
- Global Options should process before anything else.
=> Have Global Options run before command and sub-command processing

pkg/cli/get/resources/getter.go, tools/vcs/manager.go
=> Enable the use of files for components and don't fail on same repo

cmd/compliance-masonry/compliance-masonry.go
Fixes the issue when running the `compliance-masonry` command like so:
- `./somedir/compliance-masonry`
- `../../../somedir/compliance-masonry`
=> Make sure to account if compliance-masonry path is in a subdirectory

pkg/cli/get/resources/getter.go
=> Error in duplicate key in Map is detected

pkg/cli/export/export.go
=> Fix Export typos

.goreleaser.yml, Makefile, cmd/compliance-masonry/compliance-masonry.go
- Fix homebrew installs
- Search `env $PATH` in cause masonry executable cannot be found
=> More goreleaser fixes

pkg/cli/docs/gitbook/gitbookCertification.go, pkg/cli/docs/gitbook/gitbookCertification_test.go, test/fixtures/exports_fixtures/complete_export/standards/NIST-800-53-AC-2.md, test/fixtures/exports_fixtures/complete_export/standards/NIST-800-53-AC-6.md, test/fixtures/exports_fixtures/complete_export/standards/NIST-800-53-CM-2.md, test/fixtures/exports_fixtures/complete_export/standards/PCI-DSS-MAY-2015-1.1.1.md, test/fixtures/exports_fixtures/complete_export/standards/PCI-DSS-MAY-2015-1.1.md, test/fixtures/exports_fixtures/complete_export/standards/PCI-DSS-MAY-2015-2.1.md, test/fixtures/exports_fixtures/complete_export_with_markdown/standards/NIST-800-53-AC-2.md, test/fixtures/exports_fixtures/complete_export_with_markdown/standards/NIST-800-53-AC-6.md, test/fixtures/exports_fixtures/complete_export_with_markdown/standards/NIST-800-53-CM-2.md, test/fixtures/exports_fixtures/complete_export_with_markdown/standards/PCI-DSS-MAY-2015-1.1.1.md, test/fixtures/exports_fixtures/complete_export_with_markdown/standards/PCI-DSS-MAY-2015-1.1.md, test/fixtures/exports_fixtures/complete_export_with_markdown/standards/PCI-DSS-MAY-2015-2.1.md
=> Add space after comments hashtag

Makefile
Now that `git tag` is done properly, we should get the version with `git describe`
=> Fix GIT version in Makefile

internal/constants/constants.go, internal/utils/masonryutil.go, pkg/cli/docs/gitbook/gitbook.go, pkg/cli/docs/gitbook/gitbookCertification.go, pkg/cli/docs/gitbook/gitbookComponents.go, pkg/cli/docs/gitbook/gitbookSummaries.go, pkg/cli/docs/gitbook/gitbook_test.go, tools/fs/fs.go
- Add file permissions constants
- Files shouldn't be executable
- Files shouldn't use spaces in file names for multi-OS support
=> Fix file names and permissions

pkg/cli/validate/validate.go, pkg/cmd/masonry/cmd.go, validate/validate.go
Over the time, I have seen many malformed opencontrol contents. Here is very simple `masonry validate` command that will print out any problems identified in your opencontrol masonry.
How to test:
$ cd MY_OPENCONTROL_DIR/
$ masonry get
$ masonry validate
=> New Feature `masonry validate` command

README.md
Includes snippet in README on installation for macOS via [brew](https://brew.sh/) with the [opencontrol homebrew tap](https://github.com/opencontrol/homebrew-compliance-masonry) 👍
=> Include homebrew installation doc snippet

.goreleaser.yml
replacement PR of https://github.com/opencontrol/compliance-masonry/pull/353
In order to use `.goreleaser.yml` for building and releasing `masonry` with up to date versions of goreleaser, the [few deprecations as noted here on goreleaser's site should be updated](https://goreleaser.com/deprecations/) so the config is compatible with newer versions of goreleaser.
for transparency: using this version of goreleaser...
```sh
goreleaser -v
goreleaser version 0.142.0
commit: e014ad0ae88480406206c7758f3607168b45ced9
built at: 2020-08-22T22:00:14Z
built by: goreleaser
```
...threw these errors:
```sh
$ goreleaser check
• loading config file       file=.goreleaser.yml
⨯ command failed            error=yaml: unmarshal errors:
line 31: field archive not found in type config.Project
line 39: field …
```
=> uplift goreleaser config beyond noted deprecations

validate/validate.go
Fail soft instead. Example of failure message:
Component RHEL CoreOS 4 references standard NIST-800-531, however that cannot be found in the workspace
Addressing:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13f28ee]
goroutine 1 [running]:
github.com/opencontrol/compliance-masonry/validate.validateComponent(0x154d500, 0xc000097c80, 0x154d5c0, 0xc00165c000, 0x0, 0x0, 0x0)
github.com/opencontrol/compliance-masonry/validate/validate.go:43 +0x22e
github.com/opencontrol/compliance-masonry/validate.Validate()
github.com/opencontrol/compliance-masonry/validate/validate.go:19 +0x12a
github.com/opencontrol/compliance-masonry/pkg/cli/validate.NewCmdValidate.func1(0xc0001a4b00, 0x17e8c98, 0x0, 0x0) …
```
=> Do not fail hard when someone mistypes standard key

.circleci/config.yml, .github/workflows/build.yml
This allows testing to happen using GH actions. MacOS and Windows builds are failing their tests on different items, so they will have to be added later.
=> Enable GH Actions for linux
